DROP TABLE IF EXISTS TBL_EMPLOYEES;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);


DROP TABLE IF EXISTS ACTIVATION_NOTIFICATION;
CREATE TABLE ACTIVATION_NOTIFICATION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  mobile_number VARCHAR(250) NOT NULL,
  activation_status VARCHAR(250) NULL,
  order_id VARCHAR(250) NULL,
);